config/routes.rb
MeetGoDo::Application.routes.draw do

  match '/matches', to: 'matches#show'

  resources :users
  resources :vacations
  resources :trips
  resources :trip_codes, only: [:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :person_surveys, only: [:new, :create, :destroy]
  resources :trip_surveys, only: [:new, :create, :destroy]
  get "persons/new"

  root to: 'static_pages#home'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/newtrip', to: 'trips#new'
  match '/tripsurvey', to: 'trip_surveys#new'
  match '/personsurvey', to: 'person_surveys#new'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  has_many :vacations
  has_many :people, dependent: :destroy do
    def primary
      where(:is_primary => true).first
    end
  end
#  has_one  :primary_person, :class_name=> "Person", 
#       :conditions => {:is_primary => true}

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @person = @user.people.primary
    @person_survey = @person.person_survey
    @trips = @person.trips
  end

  def new
    @user = User.new
  end

  def create
    local_params = params
    person_params = local_params[:user][:person]
    local_params[:user].delete("person")
    @user = User.new(local_params[:user])

    if @user.save
      @person = @user.people.new(person_params)
      @person.is_primary = true
      if @person.save
        sign_in @user
        flash.now[:success] = "Welcome to meet go do!"
        redirect_to personsurvey_path
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="signup-container">

<% provide(:title, 'Sign up') %>
<h1 class="page-title">sign up</h1>

    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
	  
      <%= f.fields_for(:person) do |ef| %>
        <%= ef.label :name %>
        <%= ef.text_field :name %>
      <% end %>
	  

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation %>
	  

      


<br><br>
      <%= f.submit "Create my account", class: "btn btn-standout" %>
    <% end %>

</div>

app/views/users/show.html.erb
<div class="show-user-container">

<% provide(:title, @person.name) %>

<h1 class="page-title">Hello <%= @person.name %>!</h1>
<%= button_to "create new trip", newtrip_path, class: "btn btn-large btn-standout" %>
<% if @trips.count > 0 %>
  <table class="table">
	  <thead>
		<tr>
		  <td class="trip-description"><b>Name</b></td>
		  <td class="trip-description"><b>Location</b></td>
		  <td class="trip-description"><b>Start Date</b></td>
		  <td class="trip-description"><b>End Date</b></td>
		</tr>
	  </thead>

    <% @trips.each do |t|%>
      <tr>
	  <td class="trip-description"><%= t.vacation.name %></td>
	  <td class="trip-description"><%= t.vacation.location %></td>
	  <td class="trip-description"><%= t.vacation.date_start %></td>
	  <td class="trip-description"><%= t.vacation.date_end %></td>
	  <!--<td><%= button_to "edit", "#", class: "btn btn-standout" %></td>-->
	  <td>
            <%= form_tag( matches_path, method: "get" ) do %>
              <%= hidden_field_tag( :trip_id, t.id ) %>
              <%= submit_tag("see matches", class: "btn btn-standout") %>
            <% end %>
          </td>
	 
	  </tr>
    <% end %> 
  </table>
<% end %>

</div>