config/routes.rb
MeetGoDo::Application.routes.draw do

  match '/matches', to: 'matches#show'

  resources :users
  resources :vacations
  resources :trips
  resources :trip_codes, only: [:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :person_surveys, only: [:new, :create, :destroy]
  resources :trip_surveys, only: [:new, :create, :destroy]
  get "persons/new"

  root to: 'static_pages#home'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/newtrip', to: 'trips#new'
  match '/tripsurvey', to: 'trip_surveys#new'
  match '/personsurvey', to: 'person_surveys#new'

end

app/views/layouts/_footer.html.erb
      </div>
    </div>
  </div>
<div class="navbar navbar-fixed-bottom">
      <div class="container-fluid footer-container">
		<div class="row-fluid">
			<div class="span2"></div>
			<div class="span8 footer">
				<p class="pull-left">©Meet Go Do 2013</p>
				<p class="pull-right">Contact at jhaimson@mit.edu or jessmand@mit.edu</p>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span2">
          </div>
          <div class="span8 top">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <div class="brand"><%=link_to image_tag("logo.png", height: "75", width: "75", alt: "meet. go. do. logo"), root_path %></div>
            <div class="nav-collapse">
              <ul class="nav nav-pills">
                <% if signed_in? %>
                  <li <% if current_page?(@current_user) %> class="active"<% end %>><%= link_to "My Trips", @current_user %></li>
                <% else %>
                  <li <% if current_page?(root_path) %> class="active"<% end %>><%= link_to "Home", root_path %></li>
                <% end %>
                <li <% if current_page?(about_path) %> class="active"<% end %>><%= link_to "About", about_path %></li>
                <li <% if current_page?(contact_path) %> class="active"<% end %>><%= link_to "Contact", contact_path %></li>
              </ul>
              <div class="btn-group btn-signin">
                <% if signed_in? %>
	          <button class="btn btn-standout dropdown-toggle" data-toggle="dropdown"><%= @current_user.people.primary.name + " "%> <span class="caret"></span></button>
                  <ul class="dropdown-menu signin-form">
                    <li><%= link_to "My Account", "#", method: "get" %></li>
                    <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
                  </ul>

                <% else %>
                  <button class="btn btn-standout dropdown-toggle" data-toggle="dropdown">Sign In <span class="caret"></span></button>
                  <ul class="dropdown-menu signin-form">
                    <%= form_for(:session, url: sessions_path, html: { class: "signin-form" }) do |f| %>
                      <% # render 'shared/error_messages' %>
                      <li><%= f.text_field :email, placeholder: "Email" %></li>
                      <li><%= f.password_field :password, placeholder: "Password" %></li>
                      <li><%= f.submit "Enter", class: "btn btn-standout" %></li>
                    <% end %>
                  </ul>
                <% end %>
              </div>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid partial-height">
    <div class="row-fluid full-height">
      <div class="span2">
      </div>
      <div class="span8 body-background full-height">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">   
  <title>meet. go. do. | <%= yield(:title) %></title>   
  <meta name="description" content="meet. go. do. is a unique way to find friends with the same vacation plans as you. Get matched with people on the same vacation who have similar interests as you!"> 
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>  
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>  
  <![endif]--> 
</head>
<body>
  <%= render 'layouts/header' %>

  <!--Flash code for alerts -->
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  <!-- end flash code -->

  <%= yield %>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>